### ISSUE TITLE
Develop heterozygosity QC metric

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#101]

**Comment by niemasd** [comment]
For any given sample, the variant call output has allele frequencies for every called variant. We will need to talk with stakeholders to see what exact biological question is being asked to formalize, but I imagine we can do something with allele frequencies of a given sample (e.g. how many variants have an allele frequency close to 50%, or something like that)

**Comment by kmfisch** [comment]
closed with addition of #105
