### ISSUE TITLE
Explore AWS Cloud Formation

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#103]
https://aws.amazon.com/cloudformation/

https://aws.amazon.com/cloudformation/resources/templates/

**Comment by rob-knight** [comment]
This was a request from AWS to make things easier for users -- I think we would need more guidance from them to do this in a useful way although it might be useful to point the new RTL UX team at (see my email today for who they are).
