### ISSUE TITLE
Implement heterozygosity metrics and include in QC summary

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#105]
Implement heterozygosity metrics used by Niema and Karthik and include in the QC summary

**Comment by kmfisch** [comment]
see #104

**Comment by rob-knight** [comment]
Assuming that Niema's output now matches Karthik's, yes this is high priority and should be implemented for the next run. Remember that this can be used for QC for clinical samples but should NOT be used for QC for wastewater samples (because wastewater will typically be mixed).

**Comment by AmandaBirmingham** [comment]
Closed in favor of #104
