### ISSUE TITLE
Change to per run tree building instead of cumulative

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#106]
If possible with minimal effort, give an option for selecting specific samples to include by run id and sample id and cumulative all time samples (current method).

**Comment by AmandaBirmingham** [comment]
@rob-knight The CCBB pipeline treats lineage assignment (via pangolin) and tree-building (via iqtree/emperor) as two separate steps. Both of these steps are currently performed on cumulative data. Should we now perform both steps on per-run data instead, or just the tree-building one?

**Comment by AmandaBirmingham** [comment]
@rob-knight also please confirm: should per-run tree-building still include "historical" wastewater/andersen lab sequences?

**Comment by AmandaBirmingham** [comment]
@kmfisch I think it is basically easy to have the option to either do this work per-run or cumulative. Per-sample is a much larger scope.

**Comment by rob-knight** [comment]
The intent is to have a "nice" reference tree/set of sequences, that could also be user-defined, that is basically static (so should not include all our historical stuff like the Andersen lab and wastewater), so the new sequences have some sort of framework for interpretation. It would be worth asking Kristian or Niema or Joel if such a reference set exists already. It would be acceptable to set this up so it runs by default with no reference set, i.e. with just the sequences supplied by the user.
