### ISSUE TITLE
Move pipeline from ubuntu 16.04 to 18.04 or later

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#108]
The current pipeline runs on an Ubuntu 16.04 machine image.  Ubuntu 16.04 just moved into the last phase of its supported lifecycle (where the developers are not maintaining it except for security fixes).  Perhaps because of this the newest parallelcluster release (2.11.0) doesn’t allow creation of ubuntu 16.04 nodes anymore. 
<img width="752" alt="Screen Shot 2021-07-06 at 10 34 41 AM" src="https://user-images.githubusercontent.com/10677935/124644073-b0c96e00-de46-11eb-955f-f465963dde70.png">
(image from https://ubuntu.com/about/release-cycle)

**Comment by rob-knight** [comment]
Will be important for maintenance, might as well get it out of the way now.
