### ISSUE TITLE
Update samtools

### ISSUE THREAD

**Issue by niemasd** [ucsd-ccbb/covid_sequencing_analysis_pipeline#109]
A new version of samtools was just released, and I see that one of the features is that `samtools depth` was rewritten to be faster and more memory efficient. That's not a bottleneck of our pipeline, but it would still be good to update at some point (though not urgent):

https://github.com/samtools/samtools/releases/tag/1.13

**Comment by AmandaBirmingham** [comment]
Merged with #72
