### ISSUE TITLE
Create subset output file with lineages only from "current batch(es)"

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#19]
SummaryQC plus Pangolin output for all samples **including ones that have a FALSE acceptance test.** They will expect those Pangolin columns to be blank so we’re all good there. They don’t want one with just the Passed ones, which I assume (could be wrong) is what the current format

They want this **SummaryQC plus Pangolin to ONLY have the output from the current batch(es)**, which means we’ll still have to run it on all samples so it gets the latest pangolin update (because Kristian’s group want these) but for the Inspect ingestion they only want the newest stuff

**Comment by kmfisch** [comment]
With the specs change 3/18 this is now invalid and I'm closing.
