### ISSUE TITLE
Demux sequences in pipeline not in IGM

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#36]
Demux sequences in pipeline not in IGM.  Note that Rob says we should not use BCL2Fastq because there are much faster ways to demux and Niema has one set up.  Should be possible to stream data straight from sequencers to our data store, not wait to finish and be uploaded by IGM

--------------------------------
Katie:
oh and don’t let me forget long term we’ll want to have a way to demultiplex and have data sent directly from the sequencer to the production account S3
4:36
she says “soon…checking”

amanda  4:36 PM
Wait, WE want to demultiplex? why do we want to do that?

katie  4:37 PM
because it’s a single line command with the BCL2Fastq tool and it would allow for fast transfer of data so we dont have to wait for hours for them to do it and manually upload it to FTP and then us manually download it
4:38
and in theory if we could get it set up with the standardized sample names, etc through a metadata spreadsheet that comes with the data (we discussed that on the call today), we could try to write something to auto-kick off jobs when data arrive

**Comment by kmfisch** [comment]
Let's shelve this one for now since Kristen will be doing the de-muxing to split out different stakeholder datasets for us.
