### ISSUE TITLE
Test how pipeline acts on multiple consensus sequences for same specimen

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#41]
Will this result in fa records with the very same name occurring in multiple *-passQC.fas files? 
Can we test what pangolin does on duplicate fasta sequence name when those all get smushed into one merged.fas?
What happens for all the -summary.tsv table merging and subsetting in this case?  (Would this case result in multiple non-unique entries in e.g. the Sample column used for merging?)
Would this result in non-unique leaf names in empress (for potentially different consensus sequences)?

Issue requested by Rob Knight

**Comment by rob-knight** [comment]
This request comes from the EMPress team; should revisit after file names stabilize.
