### ISSUE TITLE
stop mapping reads once we hit a desired number of mapped reads in order to speed pipeline

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#42]
This approach was originally shelved as the runs we initially received processed in under an hour.  If larger data sets are leading to longer pipeline run times, we need to revisit this approach

https://github.com/niemasd/SD-COVID-Sequencing/blob/main/commands.md#speed-up-by-truncating-at-number-of-mapped-reads

**Comment by kmfisch** [comment]
this is also tied in with the subsampling the large files, so let's merge these two tasks at some point

**Comment by kmfisch** [comment]
closed and merged into #56
