### ISSUE TITLE
Create Deliverables folder and unnest folder structure if possible

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#47]
Copy select files into a deliverables folder to streamline deliverables to Helix and for GISAID upload 

Helix wants: untrimmed bams, consensus sequences and summary csv plus lineages. 

GISAID wants: need to check and whatever it is make it consistent so we don't have two different deliverables folders

**Comment by kmfisch** [comment]
Not sure this is still relevant but we might get asked again so we can leave it here

**Comment by rob-knight** [comment]
This will only be relevant if Helix is sending more samples, which latest communication suggests they won't. Can revisit priority if there is a new plan, timeline and budget for Helix samples.
