### ISSUE TITLE
Run lineage calling on all consensus sequences

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#49]
for the next version regardless of what happens with this indel flag thing, @amanda @adammaikai can we run pangolin on all samples that pass the acceptance test (excluding the indel flag), but keep the flag in? so change the order of how things are run so **everything** ~~delete this that has 95% coverage gets a lineage call~~, but only non flagged things (including the indel flag) gets put into the trees
*Updated re: 3/18 new specs from Kristian, Louise, Rob

**Comment by AmandaBirmingham** [comment]
Clarification: we will run pangolin on "everything" defined as "all consensus sequences".  Samples that do not generate consensus sequences will not be passed to pangolin (how would that even work?)

**Comment by AmandaBirmingham** [comment]
Closed in release 1.1.0[https://github.com/ucsd-ccbb/covid_sequencing_analysis_pipeline/tree/1.1.0](url)

**Comment by AmandaBirmingham** [comment]
Original request:

From: "Laurent, Louise" 
Date: Thursday, March 18, 2021 at 11:21 AM
Subject: Re: Indel flag and Pangolin calls
 
Hi All,
A few adjustments to the below, based on Kristian's input on this morning's 10 am call -- pending Katie/Amanda checking with Karthik and Al that these fit what Bjorn does:
 
[snip] 
 
4. Pangolin will be run on all consensus sequences, regardless of any QC information. 

[snip]
