### ISSUE TITLE
Send summary run stats to stakeholders after run processing

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#51]
For every run, after processing, email all the invitees for the Re: [Weekly call #A] Sequence and run QC meeting to provide, for the run:
fraction/percent that passed depth-gte-10 criterion
fraction/percent that are accepted

(I suggest also adding number that passes indels)

**Comment by rob-knight** [comment]
Check urgency on this -- I can see how it would be nice to have, but I don't think it should block data release etc. Would be good to know if there is a specific use case and if it has to be a push email rather than users pull from directory known to all stakeholders (which is much easier).

**Comment by rob-knight** [comment]
I think this is now obsolete
