### ISSUE TITLE
Given a list of sample ids, be able to output a folder of all the inspection files

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#54]
From Niema, 03/17/2021

**Comment by rob-knight** [comment]
Requires clarification from Niema. Also, is this a CCBB pipeline request, or an INSPECT request?

**Comment by AmandaBirmingham** [comment]
@niemasd Do you still want this functionality, and if so, can you clarify what it actually *is*? :)

**Comment by niemasd** [comment]
I don't quite remember what I meant here, but based on the title, now that I know how to use `aws s3 cp` properly, given a list of sample IDs, we can just do something like this:

```bash
for sample in $(cat samples.txt); do aws s3 cp "s3://ucsd-all/my_run/$sample/" . --recursive
```

**Comment by niemasd** [comment]
So I think we can go ahead and close this!

**Comment by AmandaBirmingham** [comment]
Closed per Niema's comment
