### ISSUE TITLE
Include fraction of bases passing identity criterion in summary csv

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#55]
analogous to how we output fraction of bases passing depth criterion
From Rob, 03/17/2021

**Comment by rob-knight** [comment]
I think this will be useful for troubleshooting but unless other people also want and will use it, it should be low priority. There are a lot of QC metrics implemented already.

**Comment by AmandaBirmingham** [comment]
Also closed in 2.0.0
