### ISSUE TITLE
Implement subsampling of data to account for large file sizes from uneven pooling and deep sequencing

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#56]
Implement subsampling of the data so that a few very large samples do not make the pipeline run time several hours incurring extra compute cost. 

(merging two previous issues into this one)

**Comment by rob-knight** [comment]
This is very important because the pipeline run time is bounded by the largest/slowest file.

**Comment by AmandaBirmingham** [comment]
@adammaikai will add parameter to run config info that specifies the number of mapped reads to take through the process.

**Comment by AmandaBirmingham** [comment]
in exitlog branch, by @adammaikai
