### ISSUE TITLE
Identify each manifest sample id as having one of 3 categories of sequencing results and transmit value to Inspect

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#58]
On Mar 19, 2021, at 10:47 AM, Laurent, Louise wrote:

Hi,

Thank you for this call. I think it was very helpful in understanding how we can proceed with reporting results in a useful and principled manner. Here are some notes:

We will report 3 categories of viral sequencing results (please provide feedback on wording):
* For samples with <70% coverage OR do not pass Pangolin lineage calling QC: "SARS-CoV-2 viral genome sequencing was performed. However, viral genome data obtained were not sufficient for viral variant determination or viral epidemiology analyses." [Lineage field and SEARCH ID field are empty]
* For samples with 70-95% coverage AND pass Pangolin lineage calling QC: "SARS-CoV-2 viral genome sequencing was performed. Viral genome data obtained are sufficient for viral variant determination, but not comprehensive enough for inclusion in viral epidemiology analyses." [Lineage field is filled, but SEARCH ID field is empty]
* For samples with >95% coverage AND pass Pangolin lineage calling QC: "SARS-CoV-2 viral genome sequencing was performed. Viral genome data obtained are comprehensive and sufficient for viral variant determination and inclusion in viral epidemiology analyses." [Lineage field and SEARCH ID field are filled]

**Comment by AmandaBirmingham** [comment]
Note to self: double-check these three categories cover all logical possibilities

**Comment by AmandaBirmingham** [comment]
Stakeholder: pls clarify what is required to "transmit" these values to INSPECT.  Is placing them in the *summary.csv file for a run adequate?

**Comment by rob-knight** [comment]
This was negotiated with the EPIC team so needs to be easily accessible as category data.
