### ISSUE TITLE
Remove indels_flagged, num_inserts_in_consensus, and num_deletions_in_consensus columns from summary files

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#62]
From: "Laurent, Louise" 
Date: Thursday, March 18, 2021 at 11:21 AM
Subject: Re: Indel flag and Pangolin calls
 
Hi All,
A few adjustments to the below, based on Kristian's input on this morning's 10 am call -- pending Katie/Amanda checking with Karthik and Al that these fit what Bjorn does:
 
1. indels_flagged, num_inserts_in_consensus, and num_deletions_in_consensus columns will be removed from the summary csv files created by the CCBB pipeline

[snip]

**Comment by rob-knight** [comment]
These will be left in for now because removing them involves changing the tests etc. Revisit an overhaul of the index system later; there are multiple views about how to do this.
