### ISSUE TITLE
For each tree-building run, make multiple phylogenetic trees (all seqs, >70% coverage seqs, >95% coverage seqs) 

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#68]
From: Rob Knight 
Date: Thursday, March 18, 2021 at 4:36 PM
Subject: Re: Indel flag and Pangolin calls

[snip]

I think we are keeping the 95% threshold for making the phylogenetic trees that will be considered as containing high-quality sequences, and also making phylogenetic trees that contain all sequences (for technical analysis, _not_ for biological interpretation). _Do we also need to make phylogenetic trees with all sequences >70% (anticipating that those below 70% will screw up the alignments so badly that the trees may not even be useful for tracking down issues with problem sequences) or is that not useful?_ [italics added]

Thanks,
Rob

**Comment by AmandaBirmingham** [comment]
Stakeholder: am I correct that both should be done for *every* tree-building run?
Stakeholder: did we ever get an answer to italicized question above?

**Comment by AmandaBirmingham** [comment]
@rob-knight Is this requirement based SOLELY on the coverage, or is it based on the 3 categories from issue #58 (which also include a check based on the pangolin qc)?

**Comment by rob-knight** [comment]
It would make sense to keep it consistent with issue #58.

**Comment by rob-knight** [comment]
…however, if it is very hard to keep it consistent with #58, doing it purely based on coverage is an acceptable solution.
