### ISSUE TITLE
Automatically rename "each file name" for a run to include sequencing run id

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#71]
From: Rob Knight
Date: Tuesday, March 23, 2021 at 3:47 PM
Subject: Re: SARS-CoV-2 Data Release Workflow

[snip] What I think has to happen is:

[snip]

- script to take the sequencing run id from the folder and write it into each file name has to be written and tested by CCBB because apparently IGM can’t commit to special-casing it relative to their usual procedure (they _might_ do it _most_ of the time…thanks but no thanks!)

[snip]

**Comment by AmandaBirmingham** [comment]
Stakeholder: pls specify "each file name"--are we talking just each fastq file, or does this apply to more kinds of files?

**Comment by kmfisch** [comment]
Stakeholder: For legacy samples, can we have the run ids appended to sample names in Inspect prior to the re- demultiplexing and renaming? Then going forward we will append run id in the pipeline.

**Comment by rob-knight** [comment]
The reason why this is hard is that the run id is only assigned on the Illumina instrument after the run has started.

Therefore, to get it in INSPECT, IGM has to communicate the run id to INSPECT after the run starts, likely by a manual and error prone process.

This is what prompted the idea that it would be easier to do it from the run folder, which CCBB has, and link the run info back to INSPECT with a single transfer of the other info CCBB has and needs to transmit, rather than multiple back and forth.

It is impossible to write the run id into the sample sheet because the run id is assigned downstream for that in the sequencer.

We considered but rejected creating a new run id under our control, writing that in the sample sheet, and using that id rather than the one assigned by the sequencer because then a table lookup would be needed each time the Illumina run id is needed, which is frequent when performing QC on samples.

**Comment by kmfisch** [comment]
Yes, understood for future samples. However, in the case of the legacy
samples we have now, we know the Run ID the sequencer assigned, and it
would be helpful if during this big re-run of everything these sample names
are created before they get to us (which is already the plan), as we're
working on ways to do a quicker transfer for just this big re-run set that
is different than the download/rename with run ID script we are tasked with
writing here, so we're trying to find shortest path so we don't need to
come up with two separate workflows for this one issue. Thoughts?

**Comment by kmfisch** [comment]
Preference from Louise to put Run ID at the end of the filename

**Comment by AmandaBirmingham** [comment]
Here is the current latest on where the sequencing run id goes; @kmfisch , pls note that it is positioned BEFORE lane/read_num/etc info.  Do you anticipate this being a problem given Louise's preference?

> From: "Sathe, Shashank"
> Date: Wednesday, March 31, 2021 at 2:47 PM
> Subject: Re: Pls confirm or deny current fastq naming convention :)
> 
> Hi Amanda,
> Yes, the main pieces will be separated by double underscores. No problem with the having single underscores in the sequencing information.
> 
> "SEARCHID__PLATEID__WELLID__SEQRUNID__LANENUMANDREADNUMETC.fastq.gz" seems to be the correct naming convention. However, who is providing which part of the file name varies for legacy and future samples
> 
> 1.	Legacy samples :
> a.	"SEARCHID__PLATEID__WELLID__SEQRUNID" part of the name will come from Inspect. I expect the "__LANENUMANDREADNUMETC" part to be added post demuxing. So, that will come from IGM. Please make sure with IGM that they are adding a double underscore on their part of the naming convention as well.
> 2.	Non-Legacy, Future Samples
> a.	However, for non-legacy, future runs, The "SEQRUNID" will not come from Inspect. Instead, CCBB will append that into the file name based on the data received from IGM.. So, Inspect will provide "SEARCHID__PLATEID__WELLID" to Kristen / IGM. SEQRUNID and LANENUMANDREADNUMETC will come to CCBB from IGM post-demux.
> 
> Hope this makes sense and that I am not off-pace with the current state of things.
> Shashank Sathe

**Comment by AmandaBirmingham** [comment]
@kmfisch note that if seqrunid goes where Shashank's email proposes (before lane number/read number/etc), then we DON'T have to do issue #87 and that would certainly be nice ...

**Comment by rob-knight** [comment]
I don’t think there is a strong preference for specific location, just that it is in there. However, it does need to be consistent between legacy and new samples. One very important point is that the names should be tested through the whole downstream pipeline before demux and re-transfer of everything...

**Comment by AmandaBirmingham** [comment]
Ok, so the final fastq file name should look like

`SEARCHID__PLATEID__WELLID__SEQRUNID__LANENUMANDREADNUMETC.fastq.gz`

CCBB will be receiving something from IGM that looks like:

`STUFF_LANENUMANDREADNUMETC.fastq.gz`

where `STUFF` *should* be `SEARCHID__PLATEID__WELLID` (although CCBB has no control over that) and `LANENUMANDREADNUMETC` will look like `S#+_L##_R#_001`. 

Note that I do NOT expect that there will be a double underscore between `STUFF` and `LANENUMANDREADNUMETC` in what we get from IGM.  As I understand it, it will therefore be up to us to insert `__SEQRUNID_` between `STUFF` and `_LANENUMANDREADNUMETC.fastq.gz`.
