### ISSUE TITLE
Capture sample metadata from input csv and output to bjorn-compatible "sample sheet metadata" csv

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#76]
From: Rob Knight 
Date: Tuesday, March 23, 2021 at 10:13 PM
Subject: Re: SARS-CoV-2 Data Release Workflow

On Mar 23, 2021, at 5:09 PM, Birmingham, Amanda wrote:

[snip]

> An example bjorn “sample sheet” (from Al a while ago) is attached; it contains (at least headers for) all the GSAID deposition fields, plus a few other fields like “Ready for release?”, “New sequences ready for release”, and “Released?”  If CCBB is providing this file (or at least a partially filled version of it) to Scripps, then we will still need a passel of metadata from Inspect up front for each sequencing run to populate this and smallish code changes to actually output it.

Correct, Shashank is supposed to be working on this

[snip]

**Comment by AmandaBirmingham** [comment]
I know the output file format but not the input file format.

**Comment by AmandaBirmingham** [comment]
Received a sample file from Shashank, followed up with these questions:

> From: "Birmingham, Amanda"
> Date: Monday, March 29, 2021 at 10:22 AM
> Subject: Re: Secure: UCSD Sequencing Samples Demographics Data Pull (03/25)
> 
> Hi, Shashank,
> Thank you for this example!  It is very helpful.  I have compared it against the info CCBB will need to send to the Andersen lab.  I have a couple of questions (1-3 below) that I think I need answers to in order to generate the necessary output.  Could you give me your feedback on them? 
> Thanks,
> Amanda
>  
> 1)
> The following fields are in my notes from when you, me, and Rob went over the gsaid metadata fields (which the Andersen lab expects to have passed to them as input to bjorn).  I am guessing maybe they don’t exist in inspect yet?  If this is the case, do you have any idea when they will be making their debut, and whether it will still be with the names given here?
> 
> 
> •	originating_lab field in inspect (Louise will specify full list of possible values)
> •	originating_lab_address in inspect
> •	project_authors in inspect
> •	project_name in inspect
> 
> 2)
> I also need to pass through the “Sample ID given by the sample provider”.  Questions:
> •	Is this going to be the “secondary_barcode” field you mentioned will be added?  Or, if it is some other field, which one?  
> •	Did anyone ever reach a firm conclusion about whether the field holding the id given by the sample provider (whichever field it is) might hold PHI?  Because CCBB is not cleared to know PHI, so we really don’t want to get that …
>  
> 3)
> Finally, in one of our earlier calls there was discussion of pulling a unique list of sample_collection_location values to see if they are a short enough list that we could simply create a mapping from inspect sample_collection_location value to gsaid location value (e.g., “UCSD” = “USA/California/San Diego”, etc).    Has that list been pulled, and if so, who are we waiting on to give us an answer?

**Comment by AmandaBirmingham** [comment]
CCBB received the below request, which I am filing as part of this issue since one way or another the contents of the gsaid deposition file will come via the sample sheet metadata csv:

> From: "Laurent, Louise"
> Date: Thursday, March 25, 2021 at 5:54 PM
> Subject: Re: Steps needed to process Legacy sequencing data
> 
> Hi All,
> 
> Currently, the fastqID includes the TubeID, and Helix uses this to re-identify the results to report to County. Since we are removing the TubeID from the fastqID, they request the following (I'm not sure if these are already in the analysis pipeline or how difficult it would be to implement if not):
> -- Include the Helix TubeID number (e.g. STM information or LP information ) as the "Sample ID given by originating laboratory" in the GISAID deposition (I think we already discussed that this is ok and part of the process, but wanted to make sure it's still in the works)

If the id she is asking for is in the "secondary barcode" value in the inspect metadata we are provided, then this is easy (it will happen by default), so I have reached out to Shashank to ask if that will indeed be the case.

**Comment by AmandaBirmingham** [comment]
@rob-knight I have a couple of questions regarding the details of this issue's requirements:

1) **What metadata value from the inspect file should go into the "Sample ID given by originating laboratory" column?**  Earlier discussions said to use "secondary_barcode", but there is no longer such a field in the metadata file (based on what I believe is the latest version I have, demographics_data_pull_0414.csv). My best guess is to use "sample_id", but especially given Louise's request above in this thread at https://github.com/ucsd-ccbb/covid_sequencing_analysis_pipeline/issues/76#issuecomment-809630255 , I want to be sure.

2) **What samples should be excluded from the metadata sent to the Andersen lab?**  Below is the *complete list* of criteria for exclusion of which I am aware. *Every sample* that does not meet one of these criteria will be passed on to the Andersen lab for their evaluation via bjorn/etc.  If there are more exclusion criteria, please let me know asap.  

_Exclude any sample that_:
a) does not have a consensus sequence OR
b) has a value of "Control Sample" in the Inspect "source" field OR
c) has a value of "Human" in the Inspect "subject_species" field AND 
        [has a value *other than* "Male" or "Female" in the Inspect "subject_gender" field OR
        has a value that is *not* a positive number in the Inspect "subject_age" field]

(BTW, those "subject_gender" and "subject_age" fields are really messy:
<img width="161" alt="Screen Shot 2021-04-22 at 2 23 48 PM" src="https://user-images.githubusercontent.com/10677935/115787328-e34ee900-a376-11eb-8715-35986a4288ab.png"> )

**Comment by rob-knight** [comment]
1. Shashank, this is sample_id, correct?

2. Unknown is allowed for gender. Also exclude fields that don’t have a specimen_type (may not be exact field name, Shashank please advise) or associated Project.

Shashank, anything else you know of?

**Comment by AmandaBirmingham** [comment]
Whoops, one more closed by 2.0.0
