### ISSUE TITLE
Retain lane information in file ID because INSPECT needs it

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#80]
Figure out what the final decision from stakeholders about whether or not lanes will ever be merged.

Kristen cannot guarantee we'll never not need to merge lanes so make sure to account for it. 

Inspect may not need to know about lane info. Consensus from group is that only IGM and CCBB will need to know about lanes but Inspectseq does not.

**Comment by AmandaBirmingham** [comment]
@kmfisch My understanding was that in one recent meeting, the idea of holding lane info in inspect was dropped. Do you have a written stakeholder request for this feature?  If so, please paste here.

**Comment by kmfisch** [comment]
We need to get the final decision in writing from them because I’m not sure where we landed on this.

**Comment by AmandaBirmingham** [comment]
Superseded by #93
