### ISSUE TITLE
Generate sample-specific metadata file for each sample that contains all of the other files for that sample

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#83]
From: "Laurent, Louise"
Date: Thursday, March 25, 2021 at 5:54 PM
Subject: Re: Steps needed to process Legacy sequencing data

Hi All,

Currently, the fastqID includes the TubeID, and Helix uses this to re-identify the results to report to County. Since we are removing the TubeID from the fastqID, they request the following (I'm not sure if these are already in the analysis pipeline or how difficult it would be to implement if not):

[the below request is covered by issue #76]
-- Include the Helix TubeID number (e.g. STM information or LP information ) as the "Sample ID given by originating laboratory" in the GISAID deposition (I think we already discussed that this is ok and part of the process, but wanted to make sure it's still in the works)
[end covered by issue #76] 

-- Can a sample-specific metadata file for each sample be included in the output folder that contains all of the other files for that sample? Alternatively (though not preferred by Helix), the summary QC+lineage file could include the Helix TubeID as a column (if all of the GISAID metadata is in that file anyway, then it should be there).

**Comment by AmandaBirmingham** [comment]
I do not even understand what "a ... file for each sample that contains all of the other files for that sample" means, so I can't envision how to implement this.  Can someone clarify?

However, I will note that the metadata that CCBB receives will be in one big file that contains info for all samples, and that we were not even planning to access that data until after all per-sample processing was finished.  Having to split that data out into per-sample files (if that is indeed what is being suggested) would be non-trivial extra work.

**Comment by rob-knight** [comment]
I think their preference is that they get the GISAID-style metadata file for all their samples that contains their supplied id in the “sample id from originating laboratory” field. I think we were not planning to deposit these but they are in INSPECT, and I don’t see why we can’t deposit them if they are from sources that specifically affirm in writing that it is ok to release those ids and it is not our fault, and also we can’t do anything about it, if they later find out they are not allowed to release them. I agree that the per-sample metadata files are not feasible.

**Comment by rob-knight** [comment]
Won't do this because it's Helix specific.
