### ISSUE TITLE
Sort samples by fastq size and assign each node samples with similar runtimes

### ISSUE THREAD

**Issue by AmandaBirmingham** [ucsd-ccbb/covid_sequencing_analysis_pipeline#90]
Niema  12:19 PM 2021-03-31
[snip]
It also might make sense to sort the samples by total FASTQ filesize before sending off to nodes: that way, hopefully each node will have samples that all have fairly similar runtimes = minimize idling as much as possible (edited)

**Comment by rob-knight** [comment]
Superseded by ViReflow (assuming that works) -- so closing in favor of #99
