### ISSUE TITLE
Implement alignment % calculation for capped reads

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#95]
Hi all,

I wrote a program called samhead to implement this functionality:

https://github.com/niemasd/SD-COVID-Sequencing/tree/main/samhead

It's written in pure C++ (no dependencies), and there's a Makefile included in the directory, so you can just compile using the make command. This is how the subsample mapping command used to look:

minimap2 -t THREADS -a -x sr ../ref/NC_045512.2.fas.mmi READ1.FASTQ.GZ READ2.FASTQ.GZ | samtools view -h -F 4 | head -NUM_READS_PLUS_3 | samtools sort --threads THREADS -o SORTED.BAM

And this is how you can change it to incorporate samhead:

minimap2 -t THREADS -a -x sr ../ref/NC_045512.2.fas.mmi READ1.FASTQ.GZ READ2.FASTQ.GZ | samtools view -h | samhead NUM_READS successful 2> SUBSAMPLED_MAPPING_STATS.TSV | samtools sort --threads THREADS -o SORTED.BAM

Note the following:
The call to "samtools view" has changed (you no longer include the "-F 4" flag, because the filtering is handled within samhead)
samhead replaces head entirely (because the truncating is handled within samhead)
Rather than specifying 3 + the number of desired mapped reads (NUM_READS_PLUS_3 when we used head), you simply specify the number of desired mapped reads (NUM_READS in the updated command). The +3 before was to account for the header lines, but samhead simply outputs all header lines automatically and doesn't include them in its output count
The number of mapped reads and unmapped reads that samhead encountered are printed to standard error, so the 2> SUBSAMPLED_MAPPING_STATS.TSV part redirects that information to a file instead
Katie, please let me know if the CCBB folks run into any issues plugging it into the current subsampling pipeline.

Best,
-Niema

On Fri, Apr 16, 2021 at 7:11 PM Niema Moshiri <a1moshir@eng.ucsd.edu> wrote:
Hi all,

I just got off the phone with Louise, and I've got an idea for how to implement this. It should be very easy to do, and it should be able to plug in right before piping to samtools. All it will do is redirect "total number of read mappings I've seen" to standard error (which can then be directed to a file) while the reads get sent to standard output (to be piped into samtools).

I have some existing super optimized code I can adapt for this, so I should be able to have it ready some time tomorrow morning. Once
it's ready, I'll provide instructions regarding how to change the subsampling pipeline to incorporate it.

Thanks!
-Niema

On Fri, Apr 16, 2021, 6:50 PM Laurent, Louise <llaurent@health.ucsd.edu> wrote:
Hi Niema,

We are finding that the capping of the reads is great, in the sense that it makes the whole run quicker. However, it is not allowing us to calculate the actually mapping percentage, because it only counts the mapped reads (so the mapping percent for every sample is 100%). Katie pulled the total number of reads in the fastq into the summary file, which is helpful for samples will fewer than 2 million reads, but not informative for those with more than 2 million mapped reads. We wanted to check with you -- in the mapping process, is there a way to "count" the reads that minimap grabs but is not able to map? Happy to chat by phone, as I don't think I'm explaining this well in writing, and it would take 2 minutes to explain live.

Louise

**Comment by kmfisch** [comment]
Hi all,

I wrote a program called samhead to implement this functionality:

https://github.com/niemasd/SD-COVID-Sequencing/tree/main/samhead

It's written in pure C++ (no dependencies), and there's a Makefile included in the directory, so you can just compile using the make command. This is how the subsample mapping command used to look:

minimap2 -t THREADS -a -x sr ../ref/NC_045512.2.fas.mmi READ1.FASTQ.GZ READ2.FASTQ.GZ | samtools view -h -F 4 | head -NUM_READS_PLUS_3 | samtools sort --threads THREADS -o SORTED.BAM

And this is how you can change it to incorporate samhead:

minimap2 -t THREADS -a -x sr ../ref/NC_045512.2.fas.mmi READ1.FASTQ.GZ READ2.FASTQ.GZ | samtools view -h | samhead NUM_READS successful 2> SUBSAMPLED_MAPPING_STATS.TSV | samtools sort --threads THREADS -o SORTED.BAM

Note the following:
The call to "samtools view" has changed (you no longer include the "-F 4" flag, because the filtering is handled within samhead)
samhead replaces head entirely (because the truncating is handled within samhead)
Rather than specifying 3 + the number of desired mapped reads (NUM_READS_PLUS_3 when we used head), you simply specify the number of desired mapped reads (NUM_READS in the updated command). The +3 before was to account for the header lines, but samhead simply outputs all header lines automatically and doesn't include them in its output count
The number of mapped reads and unmapped reads that samhead encountered are printed to standard error, so the 2> SUBSAMPLED_MAPPING_STATS.TSV part redirects that information to a file instead
Katie, please let me know if the CCBB folks run into any issues plugging it into the current subsampling pipeline.

Best,
-Niema

**Comment by kmfisch** [comment]
@rob-knight Can you please prioritize this? Particularly with respect to the legacy data.

**Comment by rob-knight** [comment]
Toppriority, required to meet Louise’s needs for interpreting good vs bad samples
