### ISSUE TITLE
Implement terashuf for shuffling subsampled reads 

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#96]
Hi Katie,

I looked into it to see how we could implement it into the subsampling pipeline, and we could simply plug in a tool called "terashuf" before the "head" command to shuffle the reads:

https://github.com/alexandres/terashuf

Specifically, recall that this is the general structure for how we currently do the subsampling:

minimap2 -t THREADS -a -x sr REFERENCE.MMI READ1.FASTQ.GZ READ2.FASTQ.GZ | samtools view -h -F 4 | head -NUM_READS_PLUS_3 | samtools sort --threads THREADS -o SORTED.BAM

What we would do is not output the SAM header in the first samtools view call (so all lines are just read alignments) by omitting the -h flag, then piping that to terashuf to shuffle the read alignments, then piping that to head, and then piping that to samtools view again but with the -h flag to add the header. In other words, we would do the following:

minimap2 -t THREADS -a -x sr REFERENCE.MMI READ1.FASTQ.GZ READ2.FASTQ.GZ | samtools view -F 4 | terashuf | samtools view -h | head -NUM_READS_PLUS_3 | samtools sort --threads THREADS -o SORTED.BAM

So the CCBB folks would be able to install terashuf on the instances that are running the subsampling workflow, and then rerun the 10M and 2M subsampling runs, and I could interpret the results given their output files.

Rob, thoughts? @rob-knight 
-Niema

**Comment by rob-knight** [comment]
We will do this once for research, does not need to be added to pipeline
